pub enum Nutrient {
    NitrogenTotal(f64),
    NitrogenNitrate(f64),
    NitrogenAmmonium(f64),
    Phosphorus(f64),
    Potassium(f64),
    Calcium(f64),
    Magnesium(f64),
    Sulfur(f64),
    Iron(f64),
    Zink(f64),
    Manganese(f64),
    Boron(f64),
    Copper(f64),
    Molybdenum(f64),
}
